name: continuous_integration

on: 
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update package manager & install make python3  graphviz pip  pipenv
      run: |
        sudo apt update -y
        sudo apt install -y make python3 python3-setuptools python3-pip graphviz
        sudo pip3 install pipenv
        make install_requirements_dev


    - name: lint
      run:
        make lint

    - name: tests
      run:
        make tests

